# Generated by Django 3.2.18 on 2023-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
