# Generated by Django 3.2.18 on 2023-03-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20230306_1414'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Categories',
        # ),
        migrations.AddField(
            model_name='comment',
            name='lot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lot_comment', to='auctions.lot'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lotimage',
            name='lot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lot_image', to='auctions.lot'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='lot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lot_rate', to='auctions.lot'),
        ),
    ]
