# Generated by Django 3.2.18 on 2023-03-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20230307_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='picture',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
