# Generated by Django 3.2.18 on 2023-03-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20230307_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='picture',
            field=models.ImageField(blank=True, default='media/no-image.jpg', upload_to='media/%Y/%m/%d'),
        ),
    ]
