# Generated by Django 3.2.18 on 2023-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_lot_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='picture',
            field=models.ImageField(blank=True, default='media/no-image.jpg', upload_to='%Y/%m/%d'),
        ),
    ]
