# Generated by Django 3.2.18 on 2023-03-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_lot_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='picture',
            field=models.ImageField(blank=True, default='media/no-image.jpg', height_field=150, upload_to='%Y/%m/%d', width_field=300),
        ),
    ]
