# Generated by Django 3.2.18 on 2023-03-07 23:39

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_lot_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='picture',
            field=models.ImageField(blank=True, default='media/no-image.jpg', upload_to=auctions.models._content_file_name),
        ),
    ]
