# Generated by Django 3.2.18 on 2023-03-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20230309_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotphoto',
            old_name='image_id',
            new_name='photo_id',
        ),
    ]
