# Generated by Django 3.2.18 on 2023-03-11 14:49

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_image_id_lotphoto_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.ImageField(blank=True, default='', upload_to=auctions.models._content_file_name),
        ),
    ]
