# Generated by Django 3.2.18 on 2023-03-17 12:30

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20230311_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='no-icon.jpg', upload_to=auctions.models._content_file_name),
        ),
    ]
