# Generated by Django 3.2.18 on 2023-03-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_user_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='lot_id',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='lotphoto',
            name='lot_id',
        ),
        migrations.RemoveField(
            model_name='lotphoto',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='lot_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotcomments', to='auctions.lot'),
        ),
        migrations.AddField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categories', to='auctions.category'),
        ),
        migrations.AddField(
            model_name='lotphoto',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagelots', to='auctions.lot'),
        ),
        migrations.AddField(
            model_name='lotphoto',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imageusers', to='auctions.photo'),
        ),
        migrations.AddField(
            model_name='rate',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auctions.lot'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
