# Generated by Django 3.2.18 on 2023-03-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20230317_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lotcategories', to='auctions.category'),
        ),
    ]
