# Generated by Django 3.2.18 on 2023-03-17 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_lot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentlots', to='auctions.lot'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratelots', to='auctions.lot'),
        ),
    ]
