# Generated by Django 3.2.18 on 2023-03-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_lot_winner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('lot', 'user'), name='watch_item'),
        ),
    ]
