# Generated by Django 3.2.18 on 2023-03-25 12:12

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_watchlist_watch_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='no-icon.jpg', upload_to=auctions.models._content_file_name),
        ),
    ]
