# Generated by Django 3.2.18 on 2023-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
