# Generated by Django 3.2.18 on 2023-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_lot_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.IntegerField(default=0),
        ),
    ]
